<a href="https://colab.research.google.com/github/Sanjar-prog/Telegram-JavaScript-Bot/blob/main/2_1_3_Arr_Or_Pr_1_Logical_set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science va Sun'iy Intellekt Praktikum

## Ma'lumotlar tahlili.
## 2.1. NumPy kutubxonasi bilan ishlash

### NumPy kutubxonasini chaqirib olish

In [ ]:
import numpy as np

### 2.1.3. Massivga yo'naltirilgan dasturlash

### Mantiqiy shart operatorlarni massiv operator sifatida qo'llash

### Shart operatori sifatida `where` dan foydalanish

### Tassavur qiling bizda ikkita ma'lumotlar (massivlar) mavjud bular: `xarr` va `yarr`. Agarda shart `True`ni qanoatlantirsa `xarr` elementini qabul qilgan aksincha esa `yarr` elementini qabul qilgan yangi massiv hosil qilinsin.

In [ ]:
# Massivlar
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5]) # xarr
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5]) # yarr

In [ ]:
# Shart
cond = np.array([True, False, True, True, False])

In [ ]:
# where
result = np.where(cond, xarr, yarr) # cond==True : xarr elementi, cond==False : yarr elementi
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [ ]:
arr = np.random.randn(4, 4)  # (4, 4) taxminiy massiv
arr

array([[-1.08545161, -1.81387474, -0.82558713, -0.47890241],
       [-1.1347427 ,  0.33350455,  0.74345456,  0.19039463],
       [-0.15028472, -0.53652321,  0.15661773, -0.39094636],
       [ 0.2329572 , -0.11763692,  1.64236772, -0.26843265]])

In [ ]:
# where
results = np.where(arr<0, -2, 2) # arr ning manfiy elementlarini -2 ga musbat elementlarin esa 2 ga almashitirish
results

array([[-2, -2, -2, -2],
       [-2,  2,  2,  2],
       [-2, -2,  2, -2],
       [ 2, -2,  2, -2]])