<a href="https://colab.research.google.com/github/Sanjar-prog/Telegram-JavaScript-Bot/blob/main/2_1_3_Arr_Or_Pr_4Sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science va Sun'iy Intellekt Praktikum

## Ma'lumotlar tahlili.
## 2.1. NumPy kutubxonasi bilan ishlash

### NumPy kutubxonasini chaqirib olish

In [ ]:
import numpy as np

### 2.1.3. Massivga yo'naltirilgan dasturlash

### Tartiblash (`Sorting`)

In [ ]:
# data
arr = np.random.rand(4) # 4 ta taxminiy elementlardan tashkil topgan massiv
arr

array([0.57109721, 0.7186782 , 0.28176962, 0.85192266])

### `sort` funkiyasi

In [ ]:
# 1 usul
sorted_arr = np.sort(arr) # arr massivini tartiblangan ko'rinishini sorted_arr joylaydi
sorted_arr

array([0.28176962, 0.57109721, 0.7186782 , 0.85192266])

In [ ]:
#  2 usul
arr.sort() # arr ning tartiblangan ko'rinishi
arr

array([0.28176962, 0.57109721, 0.7186782 , 0.85192266])

In [ ]:
# teskari tartiblash
rev_arr = -np.sort(-arr) # teskari tartibdagi arr
rev_arr

array([0.85192266, 0.7186782 , 0.57109721, 0.28176962])

In [ ]:
# 2 D array (massiv)
arr2d = np.random.randn(2, 4) # (2, 4) random massiv
arr2d

array([[0.23705814, 0.68765009, 0.02927274, 1.4104502 ],
       [0.70326876, 1.70741497, 1.53087128, 0.17829521]])

In [ ]:
# axis = 0 --> Qator
row_srt = np.sort(arr2d, axis=0) # arr2d ning xar bir qator bo'yicha tartiblangan ko'rinishi
row_srt

array([[0.23705814, 0.68765009, 0.02927274, 0.17829521],
       [0.70326876, 1.70741497, 1.53087128, 1.4104502 ]])

In [ ]:
# axis =1 --> Ustun
col_srt =np.sort(arr2d, axis=1) # arr2d ning xar bir ustun bo'yicha tartiblangan ko'rinishi
col_srt

array([[0.02927274, 0.23705814, 0.68765009, 1.4104502 ],
       [0.17829521, 0.70326876, 1.53087128, 1.70741497]])