<a href="https://colab.research.google.com/github/Sanjar-prog/Telegram-JavaScript-Bot/blob/main/2_1_3_Arr_Or_Pr_2_Arithmetic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science va Sun'iy Intellekt Praktikum

## Ma'lumotlar tahlili.
## 2.1. NumPy kutubxonasi bilan ishlash

### NumPy kutubxonasini chaqirib olish

In [ ]:
import numpy as np

### 2.1.3. Massivga yo'naltirilgan dasturlash

### Arifmetik amallar

### Ko'paytirish, bo'lish, qo'shish, ayirish va h.k amallar

In [ ]:
# data
arr1 = np.arange(6).reshape(2, 3) # 0~6 gach bo'lgan elementlardan tashkil topgan array
arr2 = np.arange(6, 12).reshape(2, 3) # 6 dan 11 gacha bo'lgan elementlardan tashkil topgan array

In [ ]:
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
# Ko'paytirish
arr1 * arr2 # arr1 ning elementlarini arr2 ning mos elementlariga ko'paytirib beradi

array([[ 0,  7, 16],
       [27, 40, 55]])

In [ ]:
# bo'lish
arr2/arr1 # arr1 ning elementlarini arr2 ning mos elementlariga bo'lib beradi

<ipython-input-6-b0ffd924afb6>:2: RuntimeWarning: divide by zero encountered in divide
  arr2/arr1 # arr1 ning elementlarini arr2 ning mos elementlariga bo'lib beradi


array([[inf, 7. , 4. ],
       [3. , 2.5, 2.2]])

In [ ]:
# qo'shish
arr1 + arr2 # arr1 ning elementlarini arr2 ning mos elementlariga qo'shib beradi

array([[ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
# ayirish
arr2 - arr1 # arr2 ning elementlaridan arr1 mos elementlarini ayirish

array([[6, 6, 6],
       [6, 6, 6]])

In [ ]:
# kvadratga oshirish (square)
arr1**2

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [ ]:
# kvadrat ildizdan (sqrt)
arr2**0.5

array([[2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])