<a href="https://colab.research.google.com/github/Sanjar-prog/Telegram-JavaScript-Bot/blob/main/_4_Boolean_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science va Sun'iy Intellekt Praktikum

## Ma'lumotlar tahlili.
## 2.1. NumPy kutubxonasi bilan ishlash

### NumPy kutubxonasini chaqirib olish

In [ ]:
import numpy as np

### 2.1.1. N-o'lchamli massiv (array)larga ishlov berish

### Bolean Indekslash

In [ ]:
# Ismlar
names = np.array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
names

array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'],
      dtype='<U8')

In [ ]:
# data
data = np.random.randn(7, 4)
data

array([[-0.60565792,  0.12700804, -1.8242602 , -0.43062141],
       [-1.11942127,  0.02095617,  0.08944693,  0.57669059],
       [ 1.01302274, -0.05636793,  0.6303634 ,  0.50107217],
       [-0.79413743, -0.34693971, -0.4925114 ,  0.15434155],
       [ 0.28367161, -0.52350378,  0.74771351, -0.17766276],
       [ 0.23642099, -0.12426613, -1.50864909,  0.73220788],
       [ 0.11029104, -1.58123987, -1.03360244, -0.48300329]])

In [ ]:
names == 'Hasan'

array([ True, False, False, False,  True, False, False])

In [ ]:
data[names == 'Hasan'] # Hasanga tegishli barcha ma'lumotlarni ajratib olish

array([[-0.60565792,  0.12700804, -1.8242602 , -0.43062141],
       [ 0.28367161, -0.52350378,  0.74771351, -0.17766276]])

In [ ]:
data[names == 'Elyor'] # Elyorga tegishli barcha ma'lumotlarni ajratib olish

array([[-0.79413743, -0.34693971, -0.4925114 ,  0.15434155],
       [ 0.11029104, -1.58123987, -1.03360244, -0.48300329]])

In [ ]:
data[names=='Hasan', 2:] # Hasanga tegishli oxirgi ikkita ustundagi ma'lumotlarni ajratib olish

array([[-1.8242602 , -0.43062141],
       [ 0.74771351, -0.17766276]])

In [ ]:
data[names != 'Hasan'] # (!=)Hasandan tashqari barcha insonlarning ma'lumotlarni ajratib olish

array([[-1.11942127,  0.02095617,  0.08944693,  0.57669059],
       [ 1.01302274, -0.05636793,  0.6303634 ,  0.50107217],
       [-0.79413743, -0.34693971, -0.4925114 ,  0.15434155],
       [ 0.23642099, -0.12426613, -1.50864909,  0.73220788],
       [ 0.11029104, -1.58123987, -1.03360244, -0.48300329]])

In [ ]:
data[~(names == 'Hasan')] # (~) yuqoridagi cell bilan bir xil natijani berar ekan

array([[-1.11942127,  0.02095617,  0.08944693,  0.57669059],
       [ 1.01302274, -0.05636793,  0.6303634 ,  0.50107217],
       [-0.79413743, -0.34693971, -0.4925114 ,  0.15434155],
       [ 0.23642099, -0.12426613, -1.50864909,  0.73220788],
       [ 0.11029104, -1.58123987, -1.03360244, -0.48300329]])

In [ ]:
print(names)
print(data)

['Hasan' 'Husan' 'Mirzabek' 'Elyor' 'Hasan' 'Javohir' 'Elyor']
[[-0.60565792  0.12700804 -1.8242602  -0.43062141]
 [-1.11942127  0.02095617  0.08944693  0.57669059]
 [ 1.01302274 -0.05636793  0.6303634   0.50107217]
 [-0.79413743 -0.34693971 -0.4925114   0.15434155]
 [ 0.28367161 -0.52350378  0.74771351 -0.17766276]
 [ 0.23642099 -0.12426613 -1.50864909  0.73220788]
 [ 0.11029104 -1.58123987 -1.03360244 -0.48300329]]


In [ ]:
mask = (names == 'Hasan') | (names == 'Husan') # "|" or (yoki)
mask

array([ True,  True, False, False,  True, False, False])

In [ ]:
data[mask] # Hasan va Husanlarga tegishli ma'lumotlarni ajratib olish

array([[-0.60565792,  0.12700804, -1.8242602 , -0.43062141],
       [-1.11942127,  0.02095617,  0.08944693,  0.57669059],
       [ 0.28367161, -0.52350378,  0.74771351, -0.17766276]])

In [ ]:
data

array([[-0.60565792,  0.12700804, -1.8242602 , -0.43062141],
       [-1.11942127,  0.02095617,  0.08944693,  0.57669059],
       [ 1.01302274, -0.05636793,  0.6303634 ,  0.50107217],
       [-0.79413743, -0.34693971, -0.4925114 ,  0.15434155],
       [ 0.28367161, -0.52350378,  0.74771351, -0.17766276],
       [ 0.23642099, -0.12426613, -1.50864909,  0.73220788],
       [ 0.11029104, -1.58123987, -1.03360244, -0.48300329]])

In [ ]:
data[data<0] = 0
data

array([[0.        , 0.12700804, 0.        , 0.        ],
       [0.        , 0.02095617, 0.08944693, 0.57669059],
       [1.01302274, 0.        , 0.6303634 , 0.50107217],
       [0.        , 0.        , 0.        , 0.15434155],
       [0.28367161, 0.        , 0.74771351, 0.        ],
       [0.23642099, 0.        , 0.        , 0.73220788],
       [0.11029104, 0.        , 0.        , 0.        ]])