<a href="https://colab.research.google.com/github/Sanjar-prog/Telegram-JavaScript-Bot/blob/main/Amaliyot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

In [3]:
A = np.array([[1,2,3,4],[5,6,7,8]])
A

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
A.shape

(2, 4)

In [5]:
T = np.array([[[1,2,3,4], [5,6,7,8]],
              [[10,11,12,13], [14,15,16,17]]])
T

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[10, 11, 12, 13],
        [14, 15, 16, 17]]])

In [6]:
T.shape

(2, 2, 4)

In [10]:
T2 = np.random.randint(10, size=(2,2,2,2))

In [11]:
T2.shape

(2, 2, 2, 2)

In [12]:
T2.size

16

In [13]:
T2

array([[[[6, 4],
         [9, 5]],

        [[9, 6],
         [5, 2]]],


       [[[2, 5],
         [1, 9]],

        [[8, 3],
         [3, 1]]]])

In [14]:
v1 = np.array([1,2,3,4])

v1*2

array([2, 4, 6, 8])

In [17]:
v1 = np.array([1,2,3,])
v2 = np.array([1,2,1,])

np.dot(v1, v2)

8

In [18]:
v1 = np.array([1,2,3,])
v2 = np.array([1,2,1,])

print("v1 + v2 is {}".format(v1 + v2))
print("v1 - v2 is {}".format(v1 - v2))

v1 + v2 is [2 4 4]
v1 - v2 is [0 0 2]


In [19]:
A = np.random.randint(5, size=(3,3))
A

array([[4, 4, 4],
       [0, 1, 3],
       [1, 4, 4]])

In [20]:
I3 = np.identity(3, dtype=int)
I3

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [21]:
I4 = np.identity(4, dtype=int)
I4

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [22]:
A

array([[4, 4, 4],
       [0, 1, 3],
       [1, 4, 4]])

In [23]:
A[0]

array([4, 4, 4])

In [24]:
A[:,0]

array([4, 0, 1])

In [25]:
A[1,1]

1

In [26]:
A1 = np.random.randint(5, size=(3,2))
A1

array([[3, 1],
       [3, 4],
       [0, 4]])

In [27]:
A2 = np.random.randint(5, size=(2,3))
A2

array([[4, 3, 0],
       [0, 2, 2]])

In [28]:
np.matmul(A1, A2)

array([[12, 11,  2],
       [12, 17,  8],
       [ 0,  8,  8]])

In [41]:
AI = A